import type { SaegCategory, SaegProduct } from '@/types/saeg';

export const MOCK_CATEGORIES: SaegCategory[] = [
  { id: 1, slug: 'tubercules-plantain', name: 'Tubercules & Plantain' },
  { id: 2, slug: 'legumes', name: 'Légumes' },
  { id: 3, slug: 'fruits', name: 'Fruits' },
  { id: 4, slug: 'viandes', name: 'Viandes' },
  { id: 5, slug: 'packs-anti-gaspillage', name: 'Packs Anti-gaspillage' },
];

const base = {
  currency: 'XAF',
  currency_symbol: 'FCFA',
  updated_at: new Date().toISOString(),
};

export const MOCK_PRODUCTS: SaegProduct[] = [
  {
    id: 101,
    slug: 'banane-plantain',
    name: 'Banane plantain',
    description: 'Plantain local idéal pour alloco, frites et plats familiaux.',
    short_description: 'Plantain frais de producteurs locaux (vente au kilo).',
    images: ['https://via.placeholder.com/800x800.png?text=Banane+plantain'],
    categories: [MOCK_CATEGORIES[0]],
    price: 900,
    regular_price: 900,
    sale_price: 0,
    unit_type: 'kg',
    price_per_kg: 900,
    step_kg: 0.25,
    min_kg: 0.25,
    stock_kg: 25,
    low_stock_threshold: 3,
    low_stock: false,
    stock_status: 'instock',
    is_daily_surplus: true,
    origin: 'Producteurs locaux',
    ...base,
  },
  {
    id: 102,
    slug: 'tomate',
    name: 'Tomate',
    description: 'Tomates fraîches pour sauces, salades et cuisson quotidienne.',
    short_description: 'Tomate fraîche (vente au kilo).',
    images: ['https://via.placeholder.com/800x800.png?text=Tomate'],
    categories: [MOCK_CATEGORIES[1]],
    price: 850,
    regular_price: 1000,
    sale_price: 850,
    unit_type: 'kg',
    price_per_kg: 1000,
    step_kg: 0.25,
    min_kg: 0.25,
    stock_kg: 2.5,
    low_stock_threshold: 3,
    low_stock: true,
    stock_status: 'instock',
    is_daily_surplus: true,
    origin: 'Producteurs locaux',
    ...base,
  },
  {
    id: 103,
    slug: 'pack-invendus-familial',
    name: 'Pack Panier invendus du jour – Familial',
    description: 'Pack mix anti-gaspillage grand format pour famille selon arrivage du jour.',
    short_description: 'Pack anti-gaspillage familial.',
    images: ['https://via.placeholder.com/800x800.png?text=Pack+Familial'],
    categories: [MOCK_CATEGORIES[4]],
    price: 7600,
    regular_price: 9000,
    sale_price: 7600,
    unit_type: 'unit',
    price_per_kg: 0,
    step_kg: 1,
    min_kg: 1,
    stock_kg: null,
    low_stock_threshold: 0,
    low_stock: false,
    stock_status: 'instock',
    is_daily_surplus: true,
    origin: 'Marché SAEG',
    ...base,
  },
  {
    id: 104,
    slug: 'viande-boeuf',
    name: 'Viande de bœuf',
    description: 'Viande de bœuf fraîche pour sauce tomate, brochettes et ragoûts.',
    short_description: 'Bœuf frais vendu au kilo.',
    images: ['https://via.placeholder.com/800x800.png?text=Boeuf'],
    categories: [MOCK_CATEGORIES[3]],
    price: 3900,
    regular_price: 4200,
    sale_price: 3900,
    unit_type: 'kg',
    price_per_kg: 4200,
    step_kg: 0.25,
    min_kg: 0.25,
    stock_kg: 12,
    low_stock_threshold: 3,
    low_stock: false,
    stock_status: 'instock',
    is_daily_surplus: true,
    origin: 'Bouchers locaux',
    ...base,
  },
  {
    id: 105,
    slug: 'ananas',
    name: 'Ananas',
    description: 'Ananas sucré, idéal en dessert et jus frais.',
    short_description: 'Ananas vendu à l\'unité.',
    images: ['https://via.placeholder.com/800x800.png?text=Ananas'],
    categories: [MOCK_CATEGORIES[2]],
    price: 1500,
    regular_price: 1500,
    sale_price: 0,
    unit_type: 'unit',
    price_per_kg: 0,
    step_kg: 1,
    min_kg: 1,
    stock_kg: null,
    low_stock_threshold: 0,
    low_stock: false,
    stock_status: 'instock',
    is_daily_surplus: false,
    origin: 'Producteurs locaux',
    ...base,
  }
];
